drop table if exists go_test.seasons;
CREATE TABLE seasons (
    id INT unsigned AUTO_INCREMENT NOT NULL PRIMARY KEY,
    year VARCHAR(4) NOT NULL,
    season VARCHAR(16) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;