DROP TABLE IF EXISTS go_test.roles;
DROP TABLE IF EXISTS go_test.staffs;
DROP TABLE IF EXISTS go_test.anime_staff_roles;
-- 役割
CREATE TABLE roles (
    id INT unsigned AUTO_INCREMENT NOT NULL PRIMARY KEY,
    num INT unsigned NULL,
    role_name VARCHAR(64) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;
-- staff
CREATE TABLE staffs (
    id INT unsigned AUTO_INCREMENT NOT NULL PRIMARY KEY,
    eng_name VARCHAR(64) NOT NULL,
    family_name VARCHAR(32) NULL,
    given_name VARCHAR(32) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX staff_eng_name (eng_name)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;
-- anime_staff_roles
CREATE TABLE anime_staff_roles (
    id INT unsigned AUTO_INCREMENT NOT NULL PRIMARY KEY,
    anime_id INT UNSIGNED NOT NULL,
    role_id INT UNSIGNED NULL,
    staff_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;
-- index foreign key
ALTER TABLE anime_staff_roles
ADD CONSTRAINT fk_staffrole_anime FOREIGN KEY (anime_id) REFERENCES animes (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE anime_staff_roles
ADD CONSTRAINT fk_staffrole_staff FOREIGN KEY (staff_id) REFERENCES staffs (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE anime_staff_roles
ADD CONSTRAINT fk_staffrole_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE ON UPDATE CASCADE;